dist: bionic
services:
- docker
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
addons:
  apt:
    update: true
    packages:
    - libgmp-dev
env:
  global:
    secure: xgayQslwyYIPEz291dKJANOGNtigIqBqyp/O4coeAPXQYD7YDNVJIBy/TJBrFbdrs3IdDDzFBrZF0ko2v3z5wAArNNYhbhpGdLm++xOV5hGgixQg+QyVKGT5VxvAbvcuFE8HS23m67YMk1uUipu9ba6stN/hGHxmfLHas2m0EclOrI/1CwHNoRAC3ox1rQDdzawIbSMNKb5InnWXTEnA3ISHJ0G/H0p3MJCKillcBlcKIzV5eRhqkIni9nZPfG5/vO1RrVa6x+SwquZnrPR3HXMF9/akf3nhKOrPuIjxUxtD+96C6hisyGUs92F1Tfe+YBi9XMyyLfxn0OQQnYXlnyS6ZwvpHPTax4oU7wS4HnACJ8scFy9RFQYzIxUJ2paPTZ7CfQpg/E2xO4q8bW9y6aTLu3MzoG96V98yIotyQPuBxXUrGYP/FRNMO5qdqI7POza89jAswR1nwlEyxy4t0bvZoR5ssdAAAeJ34z9OoQJgqiDiFdBJsanV6cL6rf8PyHW+gayYDmWbOgZTibT59YgwysFw3bZAPgR/wsD1ib95EhDW7qImS9yl9yZWWY66v5Jc5rA+nFQR4ICGab0KWltErwG1aZQqA1oIo/u7E/Cl5aGUHLjdd4ibXbR4OB/zU8wABkMWIPOk7lxIbPKuYpx3gm4eR/AWtnW7FdSirLc=
    secure: A/HOk2cf41esSvx77b0+/jJ6A9bonVraMxIBpWM5ndniS+mLxREi2+XFOlCJP/IPIKwI02/TdKXfoNQImKvkMlHfF1mpVG86268kgJ8fOxWIT1W9pO8j1gb52GsTWAdha7EWpKfvi8Xt5uaqm+v0KVJKr5LZq4m0A7gUN4CgvYNVkCMZeppiHCmNWJ3cJ7EftkXkd1AbiyzvHsNMfPqkH1CMwcMAwPjNMbyu7IQXQkzEVFnVMVYtJxS2vThHIJn/WigiugE0iMjTqNqyvUFXNhn2IxWjw0kWADXHPrvJFe1ueQfgx62GvStFdNqr8DSWtdeiH1/+5f5QaE7z1Bweh6UseD9WnTmkmTbLRvTssmWxq3z9TkQfPWdDc8ZisKz5rCHLnInZTesj0IEmDlEuA7McPtMbjuIjqYADe7/3PCqwmylewKxyooYGbu4uDN5AyPaU5PPftB6+KfGzjm4SvXiFaoPxYCk4QVQuPnm3atieXrBGLNAUQL6StryvBSFI9F+Yc35lpl7YOqoeAkBKI1XjlAL4FfSHXbNQkuRZ3tD7tVXTmrj2JvQ3+BWu2P7OYGnxLdLXW58d7qpYDZDRc1UilsvgVL+akJ95Zz//UzwxJnqJFKTfiDFIhaert5Lc/gARHVE/5o6zeNFiTPdrnmar4Q2A2uxbeCff/Atc0KU=
jobs:
  include:
  - stage: Install Stack
    script:
    - export DIR=~/.local/bin
    - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup
  - stage: Build dependencies
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build --dependencies-only
  - stage: Build Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build
  - stage: Test Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack test
  - stage: Build and Push Docker image
    script:
    - stack build --local-bin-path ./deploy/bin/ --copy-bins
    - cd ./deploy
    - docker build -t dkurilo/library-api .
    - ./docker_push
    on:
      branch: master
