dist: bionic
services:
- docker
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
addons:
  apt:
    update: true
    packages:
    - libgmp-dev
env:
  global:
  - secure: UMPN12eckx5U6UEWWcRf8uWP2pk/pAIkuCBoyOVUNZOK9j5CVK0tvJmh7w3uGCsi1KnxdBa9DBUujVPmMvIxOMPyL3CMk9QITkvZzrUHJlvC+BPS6PNiEh15ryuX1RZ7DnOk/umdzxwQfjHo1qcMLmAok+srxTr7xRsTum7v/3rcga/m9RnBOrAG4h0h9VSniXlAuDdpEAl+5x59XrB66e3Prhg4Ld75xKUxYZ6eji6vNdWCUuV/BKdsThdZcyTZIe3p374o384Kb29lvpqBsmZyB3yTe6lGrE/FuiqDVmREkNkztCcnOsXJPtN1t0TQxhhbJYyq6fIsy+6hDC8IDUzRX1xvQUJE9fFEhRec/vaEXBIdVCJjpJCfuGfRN1KDy938QqMG1X9vxfdMFAeJ2MtKhy6zxF/3rZmcbonK1GhwyyjD7TtWF19dtyJNb4rMgd6DK6EAXwq1/PKjICqztKVOtdRDeDgDYVdAU9n4oVpwupOwUlrW+y04Vu4UWOUnxY8oIDTZ+RkynQMXWQtRvDXqlgh326ymCFUteknJU2Rvt5GRyMeJYn/bVNSGq40nJVc1RySYJTbG7fV/ZlmMXlCq3QhVfSt1J45kxajRDxa29i1QrKRWvgXMQjhlW8w7iIX29Iwjt/HVRa6ceoZ1Ex7w+rC8qJfUUtjuwBzKSmg=
  - secure: hH9i84Ntc2Es1v1/mNX5MDN7F4z96l5n8mb9FMBQuxbTqsXDJNo6jQH9fTUhl+beTJe/o+7r7Cm41MsARd2V6iep354XzB5d3HFUs6839i4/61MhCXKhy3CQYtN9MKYAMsmaXw0xKt+V2374+fY+duDWr89TUD6DP4QGZq0iSD3q6mpu+/2CsJrhHFAbfB+pDZ16Ga29C09j2YR+G3vYLeYwEvCiZqN6hyTPrdzpyK4ZzC8rWHni3jnlzXF+Qi0/8QI0GTsrTtlr9EPBOFRJJ1ROQzHsWEstH6lgErJtCayXXeIRAz4cIlJ9TXo5XRYUPV8dNuYfhlWYWFIjOGXpOHngR8CpzMw3SKUFq+sx0kDX6ivDpSwreKVjtJ0WJQIFy2B/JHm4wdtobrMVU2OT/8+78bldsaeuzlyC47iYlzuneyKp9AZagyZwndtf56+yuNzgCYnPQjjxCM6tWXwH9vjzFOf98mSCxiKsLYReDnbiol7R9qasqoPggfoW5HLRMtyBBHngyaI8wHx+C/jkO0AneJalZxO5i61XF+jJfZkkDvBj2zn/asIps7xpU5vSpDTmeLpmtIHEbNEEZuGoautjDh8MAbxpT1P9QoZ3TT+rJMBJSqjF8h/hgUIfZxZJLB9xVLoTDprvmEBkgXc15+J/o7J0PX5+tBDj5+YP2AA=
jobs:
  include:
  - stage: Install Stack
    script:
    - export DIR=~/.local/bin
    - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup
  - stage: Build dependencies
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build --dependencies-only
  - stage: Build Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build
  - stage: Test Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack test
  - stage: Build Docker image
    script:
    - stack build --local-bin-path ./deploy/bin/ --copy-bins
    - cd ./deploy
    - docker build -t dkurilo/library-api .
deploy:
  provider: script
  script: bash ./deploy/docker_push
  on:
    branch: master
