dist: bionic
services:
- docker
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
addons:
  apt:
    update: true
    packages:
    - libgmp-dev
env:
  global:
  - secure: NiY5NUqc6uR2RouaPiXJqm1SceFjEk5bP80EzKqxRu8dCH95epBUjQh7QHVyhSXlzHCGUE3Ac8uC8WBwC+d6NGbhZvQDQOn3WtK9TD65NYPiBSq+IEbhurShfZQrFSygO39hBruU/tGtg94Ns8IjObo652j3qoSOEsyEhR8iRouWFwa3WWNyyu0l9qyy30y0BhD27LslCrVfQJ+ika4uchmVZK7GRheTtzSGEyk3dSr3ybE+5m4Bfr2ZPQadi3HoYmZryz1iGyt6IIwgzRNvUlEI9Gr1RRd9CxY90fLwCzgDPhn/iRx2XvbiyL4xXUResmsOKkqeTv6IyvoTnT9wkmcJAjBfamU/SF8nTO0wscScnhieGNlrDzc2rRnnqyv5CzHDX7j8ArDPoloMYw9I8Em45LXW/YDUOYKh3z/fg3cFMm+nty5lbvE6BsaX9kY3GzMiLoPYcHiCnmAqTO5ugvfx/tFm02BSNZVPJvxLpg/oxHIlOZNOQ6Bmfv7pRX9yq3FCFW6+ZxIESW2+of9G/qp/W9qFc2impPblOrqVqoVIFOkHSEtzx36b2paaDX2H47k7pB1aESfSJsy6Tjtqtiyc9sngj1tvPByegrl72c2T8x046EgOETD6EzDdXPLkSwIyANTELhzxTs/HTTtRwKbKLHnzRdlrvkMpS5CzoXI=
  - secure: kK17ky7T7aAEyKEUzs8ftmhFgPWYquQA7D30pyt5tX3IQjv2zUwAuZ35mK0xoO0d+ZMmc6dsFbZlYbjmK/CPo+8vRammd3gQyjxCOvBFB+q9z7uSSgeXe57jVQZ8KJL4D3eDSygSYBMYbVWxKCCrzhnivejd4fpiQmsJOo4/md6QUWhs+KjF314ap/g0F3URuy4VmuGsInLj1Hv9luEnmNcosHElLlPRbW3rAgoC/7Eoxh1Gc8zmxFO4/n08jPTnQ+togUoEoKsAlQzMJITdyb0GY9JXjfhfCGhNx4fhfuhHsh6y80P2rK503mhVQtCogfaNQ2TmG/HjU7A56NpQkZLn0j2dCn2cLgfew3VI9iQgrGdBZLiwwSg8ZZtIXJn2VbE0aWNQs2hWl3NqQdHObEf9fpFr2MTTcJShg8VEdn8cO4/Uf7I6GXnPRWE52N4hUWPpGWwevnVYhko+Gr4khiM3JlpL0AV3gejgJCcP7MFiqpekHcYbYcqhU6lLBipZH0eLcoWdwHQI1cEpUgwTAPke9AjY7ZiW/dOCnZfZwuUmkWXgZP56riuTDca6vlRYBJCQ/vDet9hTQu9ey9SxIGZJU7Jc0fdd8srpY2EBwXLtAf/fBMW8dPehKdBEKxCfEYij7zscdJkUzByM5l5CChNJwPWjl/oyMA1QGoCxk3M=
jobs:
  include:
  - stage: Install Stack
    script:
    - export DIR=~/.local/bin
    - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup
  - stage: Build dependencies
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build --dependencies-only
  - stage: Build Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build
  - stage: Test Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack test
  - stage: Build Docker image
    script:
    - stack build --local-bin-path ./deploy/bin/ --copy-bins
    - cd ./deploy
    - docker build -t dkurilo/library-api .
    on:
      branch: master
  - stage: Push Docker Image
    provider: script
    script: bash ./deploy/docker_push
    on:
      branch: master
