dist: bionic
services:
- docker
cache:
  directories:
  - "$HOME/.local/bin"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"
addons:
  apt:
    update: true
    packages:
    - libgmp-dev
env:
  global:
  - secure: b2qmPlY+XFH5EW82jlZnBPF1BHKOCs49LDmWLLc0VvJ5LpW7YN33CCBORuIUFtToWAF3oxvCzP5+SYFCqP95ZMAdkPiSICGxaVgJi2A9grVUPF/YITjRQhW4+r8L74ydwSUMli4BUTWxtfsmhveyTUifOd19tR6QFrXOXkGBvX1ILb9MmPFlLIX6JxzM3fG1Tw/23WrBlNb7+IqtcXGiTBYy8FuEFjKhJ2myaeWki+WZSxQKxEZ7nW7uxOd24DSOMVpG7vrGGNzVbc0owNJ8P78gV7Y2P4CyrSwr3SCh4qec6xIGNwtH3zipEkvAXIzKh7sB9rNqKXIMjEXEpvxRlc5dU809A5RpO3U1KDLk6dX8Mbmz7SDo7ksexK1eBkW/Ln8qO2bNszHkqOcEESP/JFrEhy+rNANZnGxPLt0sqnacNgYzqgNB0CIxxeNnN6NXtL7fJA740gtiD00apv+P+cJjEw0HyZ1JoUUtscHQ7qKmBAljQ9SVyQgBV6S9nMDRUUMAZaBTsjCSLCFdm60bNhMfuk29C3MbdapBQbM+Uwmw+1BuD9g78aEHVPnJlOs5i235LQ83Z6T9xcjNttx2jvNLkFtveI4L5M+eC8VBH9Jhcl1sYcnPo6mO8V6yYRAfpUV8hx8TFUciFkhakYt33C+8aKjZDPm7n6sp39L2ZTI=
  - secure: XuxudTnsJB1j9yYRQGA3Oa6L3HD3EM+J7xj3LNEdGBS1ydmGBDLksplj5N/EOAuvjeaDmG5zAcBxY99I+ZxYDt8SbAa44Tfw0NMrqDN6XYKUOKVfGhLIW+HYTGqkhV4FpIzx9HYqP3f/l04lYewmck6pZJGdM2Desl1o8d0co1jNG1dWB72GIv5huVFNhigizvRusOY2gevMzpYgHFdf8LzRbTztw+oGWJJcrKdXSYTnSgtxHA0FvyyQ4qbCxsqNBM9+MPyk1RENNt3SMeox3B2330fKYltnI4V3LfZqOURDWHHyGkh+J+ljMSygbWacTG8FGTo0dVvREEkjvPeFIs+ikpmCi+QZHHyfWwQKosMqSR8giE1I0x6Oaaba/U+ETyXuRRrN6sh519S5qZ2v4dGi+c3bniCEHEqfKrDzFFXiUVI0CRemgZuLjhodPflxz0MxuR3aZ+xrbqXqlZEq86K4BgUuDalcbNCy4g0BHLyRw7bZll1bD93CJbXtziES9sHohOLRjXMcT7cIQc2Cq+gGUkjZu1ySnvWgX9j5ueoZMBVl/uXkbEL/L5VfcBdivJKYSROVIXvfOh9yGY5s0ZU0A58gR1+2H3M6hu7ta90sepo+wjfuhL6D9o6/Akz12JpeqU2/FI1fjuZ6h/594ZlFac/dtKLAGUXyqGxCETo=
jobs:
  include:
  - stage: Install Stack
    script:
    - export DIR=~/.local/bin
    - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack setup
  - stage: Build dependencies
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build --dependencies-only
  - stage: Build Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack build
  - stage: Test Backend
    script:
    - export PATH=$HOME/.local/bin:$PATH
    - stack test
  - stage: Build Docker image
    script:
    - stack build --local-bin-path ./deploy/bin/ --copy-bins
    - cd ./deploy
    - docker build -t dkurilo/library-api .
    on:
      branch: master
  - stage: Push Docker Image
    provider: script
    script: bash ./deploy/docker_push
    on:
      branch: master
